import 'dotenv/config';

export const PORT = process.env.PORT;

export const DATABASE_URL = process.env.DATABASE_URL;
export const DATABASE_REDIS = process.env.DATABASE_REDIS;

export const ELASTIC_SEARCH_URL = process.env.ELASTIC_SEARCH_URL;
export const ELASTIC_SEARCH_USERNAME = process.env.ELASTIC_SEARCH_USERNAME;
export const ELASTIC_SEARCH_PASSWORD = process.env.ELASTIC_SEARCH_PASSWORD;

export const RABNIT_MQ_URL = process.env.RABNIT_MQ_URL;

export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;

export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
export const GOOGLE_CLIENT_SECRECT = process.env.GOOGLE_CLIENT_SECRECT;

export const FOLDER_IMAGE = 'public/images';

export const CLOUDINARY_NAME = process.env.CLOUDINARY_NAME;
export const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
export const CLOUDINARY_API_SECRECT = process.env.CLOUDINARY_API_SECRECT;

console.log(
  '\n',
  {
    PORT: PORT,
    DATABASE_URL: DATABASE_URL,
    DATABASE_REDIS: DATABASE_REDIS,

    ELASTIC_SEARCH_URL: ELASTIC_SEARCH_URL,
    ELASTIC_SEARCH_USERNAME: ELASTIC_SEARCH_USERNAME,
    ELASTIC_SEARCH_PASSWORD: ELASTIC_SEARCH_PASSWORD,

    RABNIT_MQ_URL: RABNIT_MQ_URL,

    ACCESS_TOKEN_SECRET: ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET: REFRESH_TOKEN_SECRET,

    GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRECT: GOOGLE_CLIENT_SECRECT,

    CLOUDINARY_NAME: CLOUDINARY_NAME,
    CLOUDINARY_API_KEY: CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRECT: CLOUDINARY_API_SECRECT,
  },
  '\n',
);
